---
name: collegescorecard
full_name: College Scorecard
type: app
owner_type: project
parent: collegescorecard
status: active
stage: live
testable: true
description: Engage and educate potential college students of any age or background and those who support and advise them, to find schools best suited to them.
links:
- url: https://collegescorecard.ed.gov/
  text: College Scorecard 
- url: https://collegescorecard.ed.gov/data/
  text: College Scorecard Data
partners:
- Department of Education
stack:
- JavaScript
- Jekyll
- Ruby
- Rails
- elasticsearch
contact:
- url: mailto:alexandra.bisker@gsa.gov
  text: Alex Bisker
team:
- github: ultrasaurus
- github: shawnbot
- github: meiqimichelle
- github: yozlet
- github: hollyallen
- github: diego-
milestones: 
- "June 2015: Kick-off meeting"
- "August 2015: Private beta launched"
- "September 2015: Public live launch"
impact: 3 Million site views since September 2015
licenses:
  collegescorecard:
    name: Public Domain (CC0)
    url: https://creativecommons.org/publicdomain/zero/1.0/ 
